import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
	en: {
		home: 'Home',
		search: 'Search',
		reservation: 'Reservation',
		realtimeReservationResult: 'Real Time Reservation Information',
		realtimeSearchResult: 'Real Time Search Information',
		hitCount: 'Hit Count',
		yanoljaId: 'yanolja ID...',
		yanoljaPwd: 'yanolja Password...',
		getReservation: 'Get Reservation',
		accommodationName: 'Accommodation Name',
		distance: 'Distance',
		rentReservation: 'Rent Reservation',
		stayReservation: 'Stay Reservation',
		searchHelp: 'Move 📍 to search different location',
		account: 'Account',
		googleLogin: 'Login with Google',
		googleLogout: 'Logout with Google',
		noReservation: 'No Reservation',
		checkInDate: 'Check In Date',
		checkOutDate: 'Check Out Date',
		reservationNumber: 'Reservation Number',
		reservationName: 'Reservation Name',
		cellPhone: 'Cell Phone',
		category: 'Category',
		roomPrice: 'Room Price',
		balancePrice: 'Balance Price',
		reservationAnalysisGraph: 'Reservation Analysis Graph',
		total: 'Total',
		yanolja: 'yanolja',
		goodchoice: 'goodchoice',
		gohere: 'gohere',
		pinspot: 'pinspot'
	},
	ko: {
		home: '홈',
		search: '주변가격',
		reservation: '예약현황',
		realtimeReservationResult: '실시간 예약 정보',
		realtimeSearchResult: '주변 숙박업체 실시간 요금 정보',
		hitCount: '조회수',
		yanoljaId: '야놀자 아이디...',
		yanoljaPwd: '야놀자 패스워드...',
		getReservation: '예약 가져오기',
		accommodationName: '호텔명',
		distance: '거리',
		rentReservation: '대실예약',
		stayReservation: '숙박예약',
		searchHelp: '📍를 이동해서 원하는 지역을 검색하세요.',
		account: '계정',
		googleLogin: '구글 아이디로 로그인',
		googleLogout: '구글 아이디로 로그아웃',
		noReservation: '예약이 없습니다.',
		checkInDate: '입실일자',
		checkOutDate: '퇴실일자',
		reservationNumber: '예약번호',
		reservationName: '예약자명',
		cellPhone: '휴대전화',
		category: '구분',
		roomPrice: '판매금액',
		balancePrice: '정산금액',
		reservationAnalysisGraph: '예약정보 분석 그래프',
		total: '전체',
		yanolja: '야놀자',
		goodchoice: '여기어때',
		gohere: '여기야',
		pinspot: '핀스팟'
	}
});

export default strings;
